/// Injectable Package Module for Data Layer
///
/// This module registers all @injectable annotated classes from data package
library;

import 'package:injectable/injectable.dart';

/// Data Package Module
///
/// Automatically generated by injectable_generator.
/// Include this in core package's injectable config using:
/// ```
/// externalPackageModulesBefore: [
///   ExternalModule(DataPackageModule),
/// ]
/// ```
@InjectableInit.microPackage()
void configureDependencies() {}
